// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-xTT9o-YSwVsASE0HQKB3fh1k5LlTr2c',
    appId: '1:1078324241585:web:17b6befea61209ccc8ae90',
    messagingSenderId: '1078324241585',
    projectId: 'coffeshope-d7bbc',
    authDomain: 'coffeshope-d7bbc.firebaseapp.com',
    storageBucket: 'coffeshope-d7bbc.firebasestorage.app',
    measurementId: 'G-PGEXE18TS3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAibmpAYfPJYd9DzO4RaMFz_EmIeju6bd8',
    appId: '1:1078324241585:android:3cc040e53bbcccabc8ae90',
    messagingSenderId: '1078324241585',
    projectId: 'coffeshope-d7bbc',
    storageBucket: 'coffeshope-d7bbc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvv9ZThCI9r5tniJrnwOZ0ZEscIf8-3Dg',
    appId: '1:1078324241585:ios:489dd5a9866c7d02c8ae90',
    messagingSenderId: '1078324241585',
    projectId: 'coffeshope-d7bbc',
    storageBucket: 'coffeshope-d7bbc.firebasestorage.app',
    iosBundleId: 'com.example.coffeShopProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvv9ZThCI9r5tniJrnwOZ0ZEscIf8-3Dg',
    appId: '1:1078324241585:ios:489dd5a9866c7d02c8ae90',
    messagingSenderId: '1078324241585',
    projectId: 'coffeshope-d7bbc',
    storageBucket: 'coffeshope-d7bbc.firebasestorage.app',
    iosBundleId: 'com.example.coffeShopProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-xTT9o-YSwVsASE0HQKB3fh1k5LlTr2c',
    appId: '1:1078324241585:web:b1341566d73478dec8ae90',
    messagingSenderId: '1078324241585',
    projectId: 'coffeshope-d7bbc',
    authDomain: 'coffeshope-d7bbc.firebaseapp.com',
    storageBucket: 'coffeshope-d7bbc.firebasestorage.app',
    measurementId: 'G-B7TZC03416',
  );
}
